preset: laravel

risky: false

enabled:
  - concat_with_spaces

disabled:
  - concat_without_spaces
  - trailing_comma_in_multiline_array

finder:
  exclude:
    - "tests"
    - "vendor"
  name:
    - "*.php"
  path:
    - "src"
