sudo: false

language: php
php:
    - 5.4
    - 5.5
    - 5.6

services:
  - memcached

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - printf "\n" | pecl install apcu-4.0.10
    - phpenv config-add travis.ini

install: composer install

script: phpunit
