sudo: false

language: php
php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

services:
  - memcached

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_install:
    - phpenv config-rm xdebug.ini
    - if [[ $TRAVIS_PHP_VERSION == 5.* ]]; then printf "\n" | pecl install apcu-4.0.11; fi
    - if [[ $TRAVIS_PHP_VERSION == 7.* ]]; then printf "\n" | pecl install apcu-5.1.5 apcu_bc-1.0.3; fi
    - phpenv config-add travis.ini

install: composer install
