sudo: false

language: php
php:
    - 5.5
    - 5.6

services:
  - memcached

cache:
    directories:
        - $HOME/.composer/cache

before_install: echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: composer install

script: phpunit --testsuite travis-ci
