sudo: false

language: php

env:
  - COMPOSER_PREFER=default
  - COMPOSER_PREFER=lowest

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

services:
  - memcached
  - redis-server

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - if [[ $TRAVIS_PHP_VERSION == 5.* ]]; then printf "\n" | pecl install -f apcu-4.0.11; fi
  - if [[ $TRAVIS_PHP_VERSION == 7.* ]]; then printf "\n" | pecl install -f apcu-5.1.18 apcu_bc-1.0.5; fi
  - phpenv config-add travis.ini

install:
  - "[[ $COMPOSER_PREFER == 'lowest' ]] && composer update --prefer-lowest || composer update"
