sudo: false

language: php
php:
    - 7.0
    - 7.1
    - 7.2

services:
  - memcached
  - redis-server

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_install:
    - phpenv config-rm xdebug.ini
    - if [[ $TRAVIS_PHP_VERSION == 5.* ]]; then printf "\n" | pecl install -f apcu-4.0.11; fi
    - if [[ $TRAVIS_PHP_VERSION == 7.* ]]; then printf "\n" | pecl install -f apcu-5.1.8 apcu_bc-1.0.3; fi
    - phpenv config-add travis.ini

install: composer install
