os: linux
dist: focal
language: php

env:
  - COMPOSER_PREFER=default
  - COMPOSER_PREFER=lowest

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

services:
  - memcached
  - redis-server

before_install:
  - printf "\n" | pecl install -f apcu-5.1.18 apcu_bc-1.0.5
  - phpenv config-add travis.ini

install:
  - "[[ $COMPOSER_PREFER == 'lowest' ]] && composer update --prefer-lowest || composer update"

before_script:
  - vendor/bin/php-cs-fixer fix --diff --dry-run
  - vendor/bin/psalm

script: vendor/bin/phpunit --coverage-text
